# Example Dev Environment Configuration
# Copy this file to .dev-env.yml and customize for your project

name: my-project
version: "1.0.0"

dependencies:
  - type: npm
    command: npm install
    path: .
  # - type: pip
  #   command: pip install -r requirements.txt
  #   path: ./backend

databases:
  - type: postgresql
    name: myapp_db
    version: "15"
    port: 5432
    host: localhost
    user: ${DB_USER}  # Use environment variable
    password: ${DB_PASSWORD}  # Use environment variable
    database: myapp
    migrations:
      - path: ./migrations
        command: npm run migrate
    seed:
      command: npm run seed

  # - type: redis
  #   version: "7"
  #   port: 6379
  #   host: localhost

services:
  # - type: rabbitmq
  #   version: "3.12"
  #   port: 5672
  #   management_port: 15672

# Environment variables (use .env file for secrets)
env:
  NODE_ENV: development
  # Use ${VAR_NAME} syntax to reference .env variables
  DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@localhost:5432/myapp
  # REDIS_URL: redis://localhost:6379

# Health checks to verify setup
health_checks:
  - name: database
    type: postgresql
    connection_string: postgresql://${DB_USER}:${DB_PASSWORD}@localhost:5432/myapp
  # - name: redis
  #   type: redis
  #   url: redis://localhost:6379

# Snapshot configuration
snapshot:
  include_databases: true
  include_volumes: true
  exclude_paths:
    - node_modules
    - .git
    - dist
    - build

# Docker Compose generation
docker:
  enabled: true
  output_file: docker-compose.yml
  network_name: dev-network
